# https://github.com/CaiJimmy/hugo-theme-stack-starter/tree/master
# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/margarita.png" # TODO:

[footer]
since = 2025
customText = ""

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
# emoji = "ðŸ« " # TODO: 
subtitle = """AquÃ­ encontrarÃ¡s de todo un poco, desde reviews de libros, pelÃ­culas y demÃ¡s, hasta ideas que se me pasen por la cabeza o historietas que me invento para entretenerme. Espero que disfrutes leyendo, Â¡y no dudes en volver!

Pd: todo esto no serÃ­a posible sin la ayuda y el trabajazo de Nacho. Â¡El mÃ©rito de que esta web exista es suyo!""" # TODO:

[sidebar.avatar]
enabled = true
local = true
src = "img/saturnina.jpg" # TODO:

[article]
headingAnchor = false
math = false
readingTime = true

# # TODO:
# [article.license]
# enabled = true
# default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

# TODO: categorÃ­a vs tags
[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

# TODO: Redes sociales
# [opengraph.twitter]
# site = ""
# card = "summary_large_image"
#
# [defaultImage.opengraph]
# enabled = false
# local = false
# src = ""

[colorScheme]
toggle = true
default = "light"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = false
provider = "disqus"

[comments.disqusjs]
shortname = ""
apiUrl = ""
apiKey = ""
admin = ""
adminLabel = ""

[comments.utterances]
repo = ""
issueTerm = "pathname"
label = ""

[comments.remark42]
host = ""
site = ""
locale = ""

[comments.vssue]
platform = ""
owner = ""
repo = ""
clientId = ""
clientSecret = ""
autoCreateIssue = false

[comments.waline]
serverURL = ""
lang = ""
visitor = ""
avatar = ""
emoji = ["https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo"]
requiredMeta = ["name", "email", "url"]
placeholder = ""

[comments.waline.locale]
admin = "Admin"

[comments.twikoo]
envId = ""
region = ""
path = ""
lang = ""

[comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[comments.giscus]
repo = ""
repoID = ""
category = ""
categoryID = ""
mapping = ""
lightTheme = ""
darkTheme = ""
reactionsEnabled = 1
emitMetadata = 0

[comments.gitalk]
owner = ""
admin = ""
repo = ""
clientID = ""
clientSecret = ""

[comments.cusdis]
host = ""
id = ""
